/* auto-generated by NAPI-RS */
/* eslint-disable */
/** SQLite-backed ZeroDB handle for Node (M2 vertical). */
export declare class Database {
  /** Create a new database file and open it. */
  static init(path: string): Database
  /** Open an existing database file. */
  static open(path: string): Database
  /** Release the SQLite connection (required before deleting the file on Windows). */
  close(): void
  /**
   * Register a change callback. Returns a subscription id for `unsubscribe`.
   *
   * Events (JSON): `{kind:'op', method, node, key?, opId}` for local
   * mutations, `{kind:'import', accepted, skipped}`, `{kind:'replay'}`.
   * Delivery is asynchronous (next event-loop tick). Experimental surface;
   * wire/event shapes are versioned-experimental and may change pre-freeze.
   */
  subscribe(callback: (arg: any) => void): number
  /** Remove a subscription; unknown ids are a no-op. */
  unsubscribe(id: number): void
  datastoreId(): string
  peerId(): string
  opCount(): number
  createNode(label: string): string
  deleteNode(node: string): string
  setLww(node: string, key: string, value: string): string
  getLww(node: string, key: string): string | null
  /** Get a materialized property as JSON (string, number, bool, array, or null). */
  getProp(node: string, key: string): any
  gcounterInc(node: string, key: string, n: number): string
  counterInc(node: string, key: string, n: number): string
  counterDec(node: string, key: string, n: number): string
  setAdd(node: string, key: string, value: string): string
  setRemove(node: string, key: string, value: string): string
  flagEnable(node: string, key: string): string
  flagDisable(node: string, key: string): string
  /** List nodes as JSON array of `{ id, label, deleted }`. */
  listNodes(): any
  /**
   * Run an O3 minimal query (`MATCH/WHERE/RETURN/ORDER BY/LIMIT`).
   * Returns a JSON array of row objects keyed by return item (e.g. `"t.title"`).
   */
  query(q: string): any
  /** Full inspect report as JSON (path is reported as the given string). */
  inspect(path: string): any
  replay(): void
  /** Export all ops as a JSON bundle string (format 1). */
  exportJson(): string
  /** Import a JSON export bundle. Returns `{ accepted, skipped }`. */
  importJson(json: string): any
}
