/* auto-generated by NAPI-RS */
/* eslint-disable */
/** SQLite-backed ZeroDB handle for Node (M2 vertical). */
export declare class Database {
  /** Create a new database file and open it. */
  static init(path: string): Database
  /** Open an existing database file. */
  static open(path: string): Database
  /** Release the SQLite connection (required before deleting the file on Windows). */
  close(): void
  /**
   * Register a change callback. Returns a subscription id for `unsubscribe`.
   *
   * Events (JSON): `{kind:'op', method, node, key?, opId}` for local
   * mutations, `{kind:'import', accepted, skipped}`, `{kind:'replay'}`.
   * Delivery is asynchronous (next event-loop tick). Experimental surface;
   * wire/event shapes are versioned-experimental and may change pre-freeze.
   */
  subscribe(callback: (arg: any) => void): number
  /** Remove a subscription; unknown ids are a no-op. */
  unsubscribe(id: number): void
  datastoreId(): string
  peerId(): string
  opCount(): number
  createNode(label: string): string
  deleteNode(node: string): string
  setLww(node: string, key: string, value: string): string
  getLww(node: string, key: string): string | null
  /** Get a materialized property as JSON (string, number, bool, array, or null). */
  getProp(node: string, key: string): any
  gcounterInc(node: string, key: string, n: number): string
  counterInc(node: string, key: string, n: number): string
  counterDec(node: string, key: string, n: number): string
  setAdd(node: string, key: string, value: string): string
  setRemove(node: string, key: string, value: string): string
  flagEnable(node: string, key: string): string
  flagDisable(node: string, key: string): string
  /** List nodes as JSON array of `{ id, label, deleted, props }`. */
  listNodes(): any
  createEdge(label: string, src: string, dst: string): string
  deleteEdge(edge: string): string
  listEdges(): any
  /** Apply a pin or SCHEMA IR JSON. Returns `{ schemaId, epoch }`. */
  applySchema(schemaJson: string): any
  schemaId(): string | null
  /**
   * Run an O3 minimal query (`MATCH/WHERE/RETURN/ORDER BY/LIMIT`).
   * Optional `params` bind `$name` placeholders.
   */
  query(q: string, params?: any | undefined | null): any
  /** Full inspect report as JSON (path is reported as the given string). */
  inspect(path: string): any
  replay(): void
  /** Export all ops as a JSON bundle string (format 1). */
  exportJson(): string
  /** Import a JSON export bundle. Returns `{ accepted, skipped }`. */
  importJson(json: string): any
  /**
   * Start a WebSocket sync listener. By default binds loopback only
   * (`ws://127.0.0.1:port`). Pass `allowInsecureLan: true` to bind
   * `0.0.0.0` (all interfaces) — the wire is **plaintext and
   * unauthenticated**; anyone on the network can read and write the
   * store, so only enable this on trusted LANs (mirrors the CLI's
   * `--allow-insecure-lan`). Port 0 asks the OS for a free port; the
   * actual port is returned. Each incoming connection runs one serve
   * session on its own thread (30s socket timeouts; a stalled peer
   * never blocks the accept loop or the store) and emits a
   * `{kind:'sync', role:'serve', ...}` event.
   * `push` (default true) advertises the v2 push capability: clients that
   * request it get a persistent session that streams new local ops as they
   * land. Pass `push: false` to behave like an old one-shot-only server.
   */
  serve(port: number, allowInsecureLan?: boolean | undefined | null, push?: boolean | undefined | null): number
  /** Stop the sync listener started by `serve`; no-op if not serving. */
  stopServe(): void
  /**
   * Connect to a peer's sync listener (`ws://host:port`) and run one
   * two-way session. Returns `{ accepted, skipped, sent, remoteAccepted,
   * remoteSkipped }` and emits a `{kind:'sync', role:'connect', ...}` event.
   */
  connectPeer(url: string): any
  /**
   * One RELAY 0.2.2 session against `zerodb-relay` (`ws://host:port`).
   * Handshake, submit local ops for `datastore` (default: this store's
   * id), then SYNC catch-up. An empty store may pass a peer's
   * `datastoreId()` to join that datastore. Returns
   * `{ sent, ackAccepted, ackDuplicate, ackRejected, received, applied, skipped }`.
   */
  connectRelay(url: string, datastore?: string | undefined | null): any
  /**
   * Keep this store converged with a peer (`ws://host:port`) from a
   * background thread: one session immediately, then re-sync whenever a
   * local mutation lands (dirty flag) or `intervalMs` elapses (poll floor
   * for remote changes). Failures emit `{kind:'sync-error', url, error,
   * retryInMs}` and retry with capped exponential backoff (1s..30s).
   * Returns a connection id for `disconnect`; `close()` stops all.
   *
   * Each attempt requests the v2 push capability. If the server acks,
   * the session stays open: new ops stream both ways immediately (dirty
   * flag and interval are then only the reconnect pacing). If the server
   * is push-unaware (old peer), the one-shot session runs and the dirty
   * flag + interval poll approximates live sync exactly as before.
   */
  autoConnect(url: string, intervalMs: number): number
  /** Stop an `autoConnect` background connection; unknown ids are a no-op. */
  disconnect(id: number): void
}

/**
 * Replay one KERNEL `crdt-apply` vector through the same Rust kernel the
 * core conformance harness uses. Input is the vector JSON; output is
 * `{ id, orders: [{ equivocation, error, state }] }`.
 */
export declare function applyCrdtVector(vectorJson: string): any
