[package]
name = "zerodb-core"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
blake3.workspace = true
uuid.workspace = true
thiserror.workspace = true
ed25519-dalek.workspace = true

[dev-dependencies]
serde_json.workspace = true
