[package]
name = "zerodb-storage"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zerodb-core = { path = "../zerodb-core" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true
blake3.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
uuid.workspace = true
getrandom.workspace = true
